# Generated by Django 4.0.3 on 2022-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
